# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1.0'
    - uses: futureware-tech/simulator-action@v3
      id: launch_simulator
      with:
        # model: 'iPhone 14'
        os: 'iOS'
        # os_version: '>=14.0'
    - name: Output simulator udid
      run: echo "Simulator UDID is ${{ steps.launch_simulator.outputs.udid }}"
    - name: Run tests
      run: |
       pwd
       chmod +x ./.github/scripts/run_tests.sh
       ./.github/scripts/run_tests.sh
      shell: bash
    # - name: Build
    #   run: swift build -v
    # - name: Run tests
    #   run: swift test -v
